name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 13]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.0.0

      - name: Install node
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ matrix.node }}

      - run: |
            # disable command workflow processing
            echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
            
            npm ci

      - run: |
            # disable command workflow processing
            echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
            
            npm test

      - run: |
            # disable command workflow processing
            echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
            
            npm run build
